### ISSUE TITLE
Unable to clone a project

### ISSUE THREAD

**Issue by lion1131github** [mantisbt-plugins/Cloneproject#8]
When i tried to clone a project, after filled in the project name to clone and hit the "Clone project" button, I got this

![image](https://github.com/mantisbt-plugins/Cloneproject/assets/168403021/7e15d2d6-eb4d-4248-97bb-d1103f062276)

it says the $t_dst_project_id is undefined. 
by looking at the source, i think it is a typo where  the $t_dst_project_id  should be $t_src_project_id defined in line 61.

i replace the variable name, try again, and it works.

i don't know if i am right to do this, please look into it.

**Comment by ghost** [comment]
has been fixed in version 2.06
