### ISSUE TITLE
I can't copy the project.

### ISSUE THREAD

**Issue by ZakharchukEduard** [mantisbt-plugins/Cloneproject#9]
Hi.
I want to thank you for the interesting and necessary plugins you develop. I am actively using some of them.
But the plugin Cloneproject does not work as expected.
I installed the plugin - I went to the Projects section - I selected the project I want to copy - I entered the name and description of the project - I clicked Clone project and got an error (((.

![изображение](https://github.com/mantisbt-plugins/Cloneproject/assets/34164109/e69376bc-97e5-49b6-9d7f-d383189f1328)

error

![изображение](https://github.com/mantisbt-plugins/Cloneproject/assets/34164109/c7845956-f1ca-4d2b-88b3-52180949a2a6)

**Comment by ghost** [comment]
Did you follow all steps for installation?
It looks you forgot the last step which is:
Copy manage_proj_clone.php into the root of your mantis installation

**Comment by ZakharchukEduard** [comment]
Sorry didn't finish reading the installation instructions. 
When I copied the file manage_proj_clone.php into the root - everything worked as expected.
Thanks again.
